### ISSUE TITLE
Confused: are the listed libraries installed?

### ISSUE THREAD

**Issue by dionjwa** [nielsborie/ml-docker#43]
```
 docker run --rm --name ML-env --entrypoint='' nielsborie/machine-learning-environments python3 -c 'import numpy'
```

gives:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

The same for all the listed libraries. Am I doing something wrong, or misunderstanding this image? Is it not a base with libraries preinstalled?

**Comment by nielsborie** [comment]
Hi @dionjwa 👋

The objective of this repository is to supply one or many python environments for the development of projects around machine learning. These environments include the list of libraries mentioned.
I am in the middle of a major redesign on this project and it's far from being finished ... but it's operative.

In fact, the entrypoint of the docker image already runs the `python` command so your previous command line becomes :  
```
docker run --rm --name ML-env nielsborie/machine-learning-environments:1.0.1-SNAPSHOT -c "import numpy ; print(numpy.version.version)"
```

And it will gives you : 
```
1.23.4
```

---

🧪 To start the python console : 

```bash
docker run -t --rm --name ML-env nielsborie/machine-learning-environments:1.0.1-SNAPSHOT
```

🪄 If you want to go further, I advise you to create the container and then dive in : 
```bash
docker run -i -t --rm --entrypoint='' --name ML-env nielsborie/machine-learning-environments:1.0.1-SNAPSHOT bin/bash
```

⚠️ Note that all libraries are installed in a `py39` conda environment.
```
conda activate py39
```

**Comment by nielsborie** [comment]
Hi @dionjwa, 

Hope my previous message has solved your problem.

I'm closing this issue.
