### ISSUE TITLE
Connect to h2o flow

### ISSUE THREAD

**Issue by alanchalk** [nielsborie/ml-docker#6]
Hi Niels - my students and I are using your image again this year.  Can I ask - whilst it is easy to open a notebook in the browser, on the other hand I cannot seem to connect to h2o-flow.  

When I start h2o - it would be nice to demonstrate h2o-flow from the browser.  This opens as stardard on port 54321.  However even though I expose port 54321 on the container - I cannot connect in a browser.  Did you even try this?

**Comment by nielsborie** [comment]
Hello Alan, 

Thanks again for using this docker image (which needs a bit of updating ...)!

I hadn't really tested this case and indeed even exposing the port `54321` doesn't work. 
It's always constraining when launching several services inside a container with internal/external network configurations.  

**I found a solution for your problem**, you can use the configuration `--network=host` to link the network inside the container with your local network! 
I tried it and it works, by going to [http://localhost:54321](http://localhost:54321) I have access to the h2o flow.

Here is the command  : 
`docker run --name ML-env --network=host -d -v ~/:/home/jovyan/work/ -e NB_UID=1000 --user root nielsborie/ml-docker start-notebook.sh --NotebookApp.password="sha1:b6dba7097c97:7bded30fcbd5089adb3b63496d5e68921e102a5f"`

By the way, the jupyter notebook will be accessible at port 8888 in this configuration...

I hope it helped you and your students! 
See you soon

**Comment by alanchalk** [comment]
Hi

Thanks for the quick response!

I spent almost all day yesterday.  The only thing I finally managed was to manually go into the container (sudo docker exec …. /bin/bash), manually navigate down to where h2o.jar is and start the jar.  If I do that - then for some reason it worked and I could get into flow.  Your way sounds about one million times better and I will try that immediately!

Yes the image does need a little bit of updating - I do not dare myself because I seem to break something every time I try.  In particular it is so easy for various boosting packages and vowpal wabbit to have conflicting requirements for numpy version or whatever…..  I am half tempted to update h2o - because I am sure they have a lot more in it now - and the version on this image is a year out of date…

Anyway thanks again - it is good to chat once a year :-)

I hope you are otherwise keeping healthy and safe in these crazy times…

Regards

Alan

**Comment by alanchalk** [comment]
Hi again,

By the way, I managed to my students onto google VMs - onto which they load dropbox and docker and your image.  

Which means each student has an identical environment - compared to when I started a few years ago when they were working on their laptops in their own Python environments - this is light years ahead :-)

Best regards

Alan

**Comment by nielsborie** [comment]
Hi Alan, 

> By the way, I managed to my students onto google VMs - onto which they load dropbox and docker and your image.

Very glad to hear that! It's always nice to know that what you've created can be useful for other people :)
What do you teach? And to whom? (if not indiscreet)? 

> Yes the image does need a little bit of updating 

Yes it's clear that it's time to clean up this image, I'm going to take care of updating all this! 
I also had some version problems this winter, especially with TensorFlow.

I'll take care of that shortly, stay tuned! 

Best regards,
Niels

**Comment by alanchalk** [comment]
By the way, one of the students suggested

-e NB_UID=$(id -u)

Which then works for any uid. :-)

Not indiscreet at all.  Mainly I work for an insurance company - trying to do some data science for them…..

But once a year I teach a Machine Learning elective to post grads at a Uni in London.  It is a basic course - but still keeps me on my toes. :-)

What do you do?

Look forward to an updated version if you manage to find the time :-)

Regards

Alan
