### ISSUE TITLE
Updating Libraries Docker Image

### ISSUE THREAD

**Issue by igormoreira-2** [nielsborie/ml-docker#7]
Dear Niels,

My name is Igor Marques, an MSc Business Analytics student from Queen Mary University of London. I am currently working on my dissertation project where I am building various machine learning models. My group and I are using your docker image, and I must say it is a great one, thank you! It has pretty much all packages we need at the moment. However, I have been having some issues considering that some libraries are outdated (eg.: scikit-learn, pandas, etc.). I am quite new to Docker and Containers, so I apologize in advance if my query is rather simple. 

Is it possible to update some of the libraries in your docker image? If yes, is this something I'd be able to do in my VM (I am using an instance on Google Cloud), or would that have to be done by you (assuming I wish to continue to use your docker image)? I have looked for different docker images for machine learning, but so far I have not found one as comprehensive as yours. And since we are working in a group, it would be nice to have all members using the same environment.

Thank you a lot for your help.

Regards,
Igor

**Comment by nielsborie** [comment]
Dear Igor, thanks for using it !  

Yes you can update the libraries directly inside the running container. 

Two options : 

- [ ] using Jupyter notebook : you can either use `pip` commands in a cell (ex: `!pip install -U scikit-learn` ) either use the embed terminal to install/update packages

- [ ] you can go into the container : just run `docker exec -it <docker-container-name> bash`, then you'll be "inside" the container. and you can execute the command line you want

I hope I've helped you.

Regards,
Niels

**Comment by igormoreira-2** [comment]
Thank you a lot Niels. It definitely helped, and I have updated all packages.

Best regards,
Igor

**Comment by SoufianeDataFan** [comment]
Does that mean every time I pull the docker image, I will get the last versions of each ML packages?
